language: node_js

steps:

  install:
    image: khs1994/node:git
    run:
      - npm config set cache /tmp/pcit_cache/npm
      - npm install --registry=https://registry.npm.taobao.org

  script:
    image: node:${NODE_VERSION}-alpine
    run:
      - npm test

  after_success: npm run prepublishOnly

  version_daily:
    run:
      - npm --no-git-tag-version version prerelease --preid=dev.$(date +"%Y%m%d")
    if:
      event: ['push']
      status: success
      jobs:
        - NODE_VERSION: "13"

  deploy_next:
    image: pcit/npm
    with:
      # username: yourusername
      # password: yourpassword
      email: khs1994@khs1994.com
      api_key: ${NPM_TOKEN}
      tag: next
      # registry: https://registry.npmjs.org
      # skip_verify: false
      # fail_on_version_conflict: false
      # access: public # public | restricted
    if:
      event: ['push']
      status: success
      jobs:
        - NODE_VERSION: "13"

  deploy:
    image: pcit/npm
    with:
      api_key: ${NPM_TOKEN}
      email: khs1994@khs1994.com
      fail_on_version_conflict: true
    if:
      event: ['tag']
      status: success
      jobs:
        - NODE_VERSION: "13"

jobs:
  NODE_VERSION:
    - "13"
