language: node_js

pipeline:

  install:
    image: khs1994/node:git
    command:
      - npm config set cache "/tmp/npm"
      - npm install --registry=https://registry.npm.taobao.org

  script:
    image: node:${NODE_VERSION}-alpine
    commands:
      - npm test
      - npx tsc

  version_daily:
    commands:
      - npm --no-git-tag-version version prerelease --preid=dev.$(date +"%Y%m%d")
    when:
      event: ['push']
      status: success
      matrix:
        - NODE_VERSION: 11

  deploy_next:
    # environment:
    settings:
      provider: npm
      api_key: ${NPM_TOKEN}
      email: khs1994@khs1994.com
      tag: next
      # registry:
    when:
      event: ['push']
      status: success
      matrix:
        - NODE_VERSION: 11

  deploy:
    settings:
      provider: npm
      api_key: ${NPM_TOKEN}
      email: khs1994@khs1994.com
    when:
      event: ['tag']
      status: success
      matrix:
        - NODE_VERSION: 11

matrix:
  NODE_VERSION:
    - 11
    - 10
