language: node_js

pipeline:

  install:
    command:
      - npm install --registry=https://registry.npm.taobao.org

  script:
    image: node:${NODE_VERSION}-alpine
    commands:
      - npm test
      - npx tsc

  deploy:
    # environment:
    #   - NPM_TOKEN=""
    provider: npm
    email: khs1994@khs1994.com
    when:
      event: ['tag']
      status: success
      matrix:
        - NODE_VERSION: 11

matrix:
  - NODE_VERSION: 11
  - NODE_VERSION: 10
