language: node_js

cache: npm

install: npm install

script: npm test

deploy:
  provider: npm
  email: khs1994@khs1994.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    node: 12

node_js:
  - 12
  - 10
